
  /*******************************************************************
  * CommonServices.java
  * Generated by Backendless Corp.
  ********************************************************************/
		
package in.myecash.appbase.backendAPI;

  import com.backendless.Backendless;
  import in.myecash.appbase.constants.BackendSettings;
  import in.myecash.common.database.Customers;
  import in.myecash.common.database.Merchants;


  public class CommonServices
  {
      static final String SERVICE_NAME = "CommonServices";
      static final String SERVICE_VERSION_NAME = "1.0.0";
      static final String APP_VERSION = "v1";

      private static CommonServices ourInstance = new CommonServices();

      private CommonServices(  )
      {
      }

      public static CommonServices getInstance()
      {
          return ourInstance;
      }

      public static void initApplication()
      {
          Backendless.setUrl( BackendSettings.BACKENDLESS_HOST );
          // if you invoke this sample inside of android application, you should use overloaded "initApp" with "context" argument
          Backendless.initApp( BackendSettings.APPLICATION_ID, BackendSettings.ANDROID_SECRET_KEY, CommonServices.APP_VERSION );
      }

      public void changePassword(String userId, String oldPasswd, String newPasswd)
      {
          Object[] args = new Object[]{userId, oldPasswd, newPasswd};
          Backendless.CustomService.invoke( SERVICE_NAME, SERVICE_VERSION_NAME, "changePassword", args );
      }

      public Merchants getMerchant(String merchantId)
      {
          Object[] args = new Object[]{merchantId};
          return Backendless.CustomService.invoke( SERVICE_NAME, SERVICE_VERSION_NAME, "getMerchant", args, Merchants.class );
      }

      public Customers getCustomer(String custId)
      {
          Object[] args = new Object[]{custId};
          return Backendless.CustomService.invoke( SERVICE_NAME, SERVICE_VERSION_NAME, "getCustomer", args, Customers.class );
      }

  }
